import os
from dotenv import load_dotenv

load_dotenv()

SUPABASE_URL = os.getenv("SUPABASE_URL")
SUPABASE_SECRET_KEY = os.getenv("SUPABASE_SECRET_KEY")
SUPABASE_PUBLISHABLE_KEY = os.getenv("SUPABASE_PUBLISHABLE_KEY")
STORAGE_BUCKET_XRAY = os.getenv("STORAGE_BUCKET_XRAY", "xray-images")
STORAGE_BUCKET_REPORT = os.getenv("STORAGE_BUCKET_REPORT", "pdf-reports")
STORAGE_BUCKET_PROFILE = os.getenv("STORAGE_BUCKET_PROFILE", "profile-pictures")

MAX_XRAY_UPLOAD_BYTES = int(os.getenv("MAX_XRAY_UPLOAD_BYTES", 10 * 1024 * 1024))
MAX_PROFILE_PICTURE_BYTES = int(os.getenv("MAX_PROFILE_PICTURE_BYTES", 2 * 1024 * 1024))
